# Run rubocop and the specs with GitHub Actions

name: CI

on: push

jobs:
  specs:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code repo
          uses: actions/checkout@v2

        - name: Run the specs
          run: make test
